### ISSUE TITLE
Missing file «GameObject.cs» in repository

### ISSUE THREAD

**Issue by shados250** [clashbyte/openvice#10]
Good day!

There is failed build, because it is no file «GameObject.cs» at GitHub.

Are any solves ?

![2020-09-06_19-58-07](https://user-images.githubusercontent.com/50293102/92330922-5f601f00-f07b-11ea-9d86-048347551451.png)

**Comment by Afr0** [comment]
Ooh, I forgot to upload it. Anyway, it's just an empty file, you can just create it in the Entities folder

**Comment by shados250** [comment]
Ok, i have created this one (empty file with class GameObject).

This error has gone.

### For example:

![2020-09-09_04-06-00](https://user-images.githubusercontent.com/50293102/92542637-f1218500-f251-11ea-8d1b-239d62dd7154.png)
