### ISSUE TITLE
The «OpenVice» project tries to use nonexistent fileds at the «OpenViceData SCMFile.cs» (a lot of errors like: Error CS1061 “…Does Not Contain Definition")

### ISSUE THREAD

**Issue by shados250** [clashbyte/openvice#12]
Good Day!

The «OpenVice» project tries to use nonexistent fileds at the «OpenViceData SCMFile.cs» (a lot of errors like: Error CS1061 “…Does Not Contain Definition") )

Therefore the project OpenVice could not build:

![2020-09-09_04-21-47](https://user-images.githubusercontent.com/50293102/92543834-22e81b00-f255-11ea-9740-c44449d07bb8.png)
![2020-09-09_04-24-29](https://user-images.githubusercontent.com/50293102/92543837-254a7500-f255-11ea-8d7f-7e63b9c3d5e4.png)

**Comment by Afr0** [comment]
SCMFile.cs exists. If it can’t be found, you have to add it to the project manually.

**Comment by shados250** [comment]
No. I mean another problem.

The class «SCMFile» does not have a few fields, that are used by Solution.

So it could not be compiled.

**Comment by Afr0** [comment]
Should be fixed now.

**Comment by shados250** [comment]
Yes! It builds now. Thanks a lot. I wanna run this already :)
