### ISSUE TITLE
OpenVice engine crash: System.DllNotFoundException: openal32.dll

### ISSUE THREAD

**Issue by shados250** [clashbyte/openvice#14]
Hello!

I had successfully built the solution, but after application start it is crash:
` System.DllNotFoundException: openal32.dll
   в OpenTK.Audio.AudioContext.CreateContext(String device, Int32 freq, Int32 refresh, Boolean sync, Boolean enableEfx, MaxAuxiliarySends efxAuxiliarySends)
   в OpenTK.Audio.AudioContext..ctor()`

Are any solves ?

![2020-09-09_18-51-24](https://user-images.githubusercontent.com/50293102/92622260-86ae2a80-f2cd-11ea-8597-6e795f92e0cd.png)

**Comment by Afr0** [comment]
https://openal.org/downloads/

**Comment by shados250** [comment]
Thanks.

Also here is an downloaded archive, If the link stops working one day :)

[oalinst.zip](https://github.com/clashbyte/openvice/files/5196858/oalinst.zip)
